name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        #run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  
      - run: docker build -t dockerslc14/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true dockerslc14/react-test npm test

      - run: docker build -t dockerslc14/multi-client ./client
      - run: docker build -t dockerslc14/multi-nginx ./nginx
      - run: docker build -t dockerslc14/multi-server ./server
      - run: docker build -t dockerslc14/multi-worker ./worker

      - run: docker push dockerslc14/multi-client
      - run: docker push dockerslc14/multi-nginx
      - run: docker push dockerslc14/multi-server
      - run: docker push dockerslc14/multi-worker

      #- name: Generate deployment package
      #  run: zip -r deploy.zip . -x '*.git*'

      #- name: Deploy to EB
      #  uses: einaregilsson/beanstalk-deploy@v18
      #  with:
      #    aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #    aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #    application_name: multi-gh
      #    environment_name: Multigh-env
      #    existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
      #    region: us-east-1
      #    version_label: ${{ github.sha }}
      #    deployment_package: deploy.zip